### PR TITLE
Fixed a problem handling 'arrow()' and 'unit()' functions needed for …

### LINKED ISSUE #11: Does not plot due to error "cannot find arrow() function"
Dear François,

thank you for the really nice network plotting function. Unfortunately the code broke during one of the last commits so that plotting does not work anymore. The following example is taken from the examples listed in the ggnet2 documentation and produces the error:

start R
library(ggnet)

  x           <- 10
  ndyads      <- x * (x - 1)
  density     <- x / ndyads
  m           <- matrix(0, nrow = x, ncol = x)
  dimnames(m) <- list(letters[ 1:x ], letters[ 1:x ])
  m[ row(m) != col(m) ] <- runif(ndyads) < density
  m

  # random undirected network
  n <- network::network(m, directed = FALSE)
  n

  ggnet2(n, label = TRUE)

I cloned your repository, fixed this and other problems and will submit a pull request.

Best,
Christoph

### PR DESCRIPTION
**Pull request by schmidtchristoph**
…plotting, which closes #11. In particular, the grid package was added to require_pkgs and adding grid:: prefix to arrow() and unit() calls (to eliminate devtools::check() note 'no visible global function definition') in 'ggnet()' and 'ggnet2()'. Re-organization of tests so that they now would not fail to reproduce the error in issue #11 (if it had not been fixed). Checking the package with devtools::check() now results in Status: OK (no error, warning or note).

### CODE REVIEW

**Comment by schmidtchristoph** [comment]
Dear François,

this is my proposed pull request. Maybe it is useful for you.

Best regards,
Christoph

**Comment by schmidtchristoph** [comment]
Maybe it would be a good idea to follow Hadley Wickham's advice (in his book on writing R packages) to include all package dependencies in the Imports field in the description file and use the prefix package::function notation in the code. This makes the code easier to read and one does not need the require() / require_pkgs() functions (which were used explicitly in the tests and prevented them from failing).

**Comment by briatte** [comment]
I'll keep this archived in case we need it, but the forthcoming release of `ggplot2` 1.1.0 should solve the matter (I've been using it for several weeks, it should be out soon).

**Comment by schmidtchristoph** [comment]
Thanks for the information and good to know. I made these changes to ggnet to use it for a package I'm developing at work. With the development version of ggplot2 - is ggnet working without the require() calls?  Keep up the good work!

**Comment by briatte** [comment]
All tests run fine with the dev version of `ggplot2`, so I suspect that yes, all problems will be solved by using that version.

**Pull request closed without merging**
